### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by franciscotln** [krawaller/callbag-proxy#1]
I'm getting this error by running this code:
```js
const { forEach, map, pipe, take } = require('callbag-basics');
const create = require('callbag-create');
const startWith = require('callbag-start-with');
const makeProxy = require('callbag-proxy');

const secondProxy$ = makeProxy();

const first$ = pipe(
  secondProxy$,
  map(x => x * 10),
  take(5)
);

const second$ = pipe(
  first$,
  map(x => x + 1),
  startWith(1)
);

secondProxy$.connect(second$);

pipe(
  first$,
  forEach((x) => {
    console.log('FIRST => ', x);
  })
);

pipe(
  second$,
  forEach((x) => {
    console.log('SECOND => ', x);
  })
);
```
Am I doing something wrong?

**Comment by krawaller** [comment]
I've just done a quick read-through, but - isn't the whole code synchronous? That would definitely blow the stack.

For your example to work you would need to add a "delay" operator to one or both of the streams.

Here's an older demo of mine doing exactly that with RxJS:

![pingpong](https://user-images.githubusercontent.com/249764/38014391-edbb0d9c-3268-11e8-8790-d92a3682373b.gif)

**Comment by franciscotln** [comment]
Oh I see then, I'll add a delay to one of them and re-check. Thanks 👍
